version: '2'

services:

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring_microservice
      MYSQL_PASSWORD: root

#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#     - "5672:5672"
#     - "15672:15672"